# This is a basic workflow to help you get started with Actions

name: Package for windows

# Controls when the action will run. 
on:
  push:
#  release:
#    types: [created]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on

    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run build.py
        run: |
          sudo apt-get install x11vnc net-tools freeglut3-dev
          sudo x11vnc -forever -loop -noxdamage -repeat -create -rfbport 5900 -shared &
          python -m pip install wheel
          python -m pip install -r requirements.txt
          DISPLAY=:1 python build.py

#      - name: Upload the artifacts
#        uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          files: dist/*

